version: '3.1'

services:
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_routes:/var/lib/postgresql/data/

volumes:
  postgres_data_routes: