version: '3.1'

services:
  routes:
    build:
      context: ./app
    ports:
      - "80:5000"
    env_file:
      - .env
    command: >
      sh -c "python database.py &&
             gunicorn --bind 0.0.0.0:5000 wsgi:app"
    networks:
      - test_project
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.19
    expose:
      - 5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_routes:/var/lib/postgresql/data/
    networks:
      - test_project

volumes:
  postgres_data_routes:

networks:
  test_project: